#include "berry.h"
#include "script/script_runtime.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void put_u16(uint8_t *p, uint16_t value)
{
    p[0] = (uint8_t)value; p[1] = (uint8_t)(value >> 8);
}

static void put_u32(uint8_t *p, uint32_t value)
{
    p[0] = (uint8_t)value; p[1] = (uint8_t)(value >> 8);
    p[2] = (uint8_t)(value >> 16); p[3] = (uint8_t)(value >> 24);
}

static int fail(const char *message, const char *path)
{
    fprintf(stderr, "fw_scriptc: %s%s%s\n", message, path ? ": " : "", path ? path : "");
    return 1;
}

static int compile_only_native(bvm *vm)
{
    be_pushnil(vm);
    be_return(vm);
}

int main(int argc, char **argv)
{
    const char *input = NULL, *output = NULL;
    char temporary[1024];
    FILE *file;
    uint8_t *payload, header[SCRIPT_FWSC_HEADER_SIZE] = {0};
    long length;
    bvm *vm;
    int result;

    if (argc == 4 && strcmp(argv[2], "-o") == 0) {
        input = argv[1]; output = argv[3];
    } else {
        fprintf(stderr, "usage: fw_scriptc INPUT.be -o PROGRAM.fwsc\n");
        return 2;
    }
    if (snprintf(temporary, sizeof(temporary), "%s.berry-bytecode.tmp", output) >= (int)sizeof(temporary))
        return fail("output path too long", output);
    vm = be_vm_new();
    if (!vm) return fail("could not create compiler VM", NULL);
    be_regfunc(vm, "configure_outputs", compile_only_native);
    be_regfunc(vm, "define_control", compile_only_native);
    be_regfunc(vm, "control_get", compile_only_native);
    be_regfunc(vm, "note_is_on", compile_only_native);
    be_regfunc(vm, "note_started", compile_only_native);
    be_regfunc(vm, "output_set", compile_only_native);
    be_regfunc(vm, "tick_index", compile_only_native);
    result = be_loadmode(vm, input, 0);
    if (result == BE_OK) result = be_savecode(vm, temporary);
    if (result != BE_OK) {
        be_dumpexcept(vm);
        be_vm_delete(vm);
        remove(temporary);
        return fail("compilation failed", input);
    }
    be_vm_delete(vm);
    file = fopen(temporary, "rb");
    if (!file) return fail(strerror(errno), temporary);
    if (fseek(file, 0, SEEK_END) || (length = ftell(file)) < 0 ||
        length > SCRIPT_MAX_PAYLOAD || fseek(file, 0, SEEK_SET)) {
        fclose(file); remove(temporary);
        return fail("bytecode exceeds 4096-byte limit", input);
    }
    payload = (uint8_t *)malloc((size_t)length);
    if (!payload || fread(payload, 1, (size_t)length, file) != (size_t)length) {
        fclose(file); free(payload); remove(temporary);
        return fail("could not read generated bytecode", temporary);
    }
    fclose(file);
    remove(temporary);

    memcpy(header, "FWSC", 4);
    put_u16(header + 4, 1);
    header[6] = SCRIPT_RUNTIME_ID_BERRY;
    header[7] = SCRIPT_CONFIG_FLOAT32_INT32;
    put_u16(header + 8, SCRIPT_RUNTIME_ABI_VERSION);
    put_u16(header + 10, SCRIPT_FWSC_HEADER_SIZE);
    put_u32(header + 12, (uint32_t)length);
    put_u32(header + 16, script_runtime_crc32(payload, (size_t)length));
    file = fopen(output, "wb");
    if (!file || fwrite(header, 1, sizeof(header), file) != sizeof(header) ||
        fwrite(payload, 1, (size_t)length, file) != (size_t)length || fclose(file)) {
        if (file) fclose(file);
        free(payload);
        return fail("could not write container", output);
    }
    free(payload);
    return 0;
}
