#include "envelope_controls.h"

#include <cerrno>
#include <cmath>
#include <cstring>
#include <iomanip>
#include <limits>
#include <locale>
#include <spawn.h>
#include <sstream>
#include <stdexcept>
#include <sys/wait.h>

extern char** environ;

namespace envelope_controls {
namespace {
std::string real(double value)
{
    float const encoded = static_cast<float>(value);
    if (!std::isfinite(encoded) || (value != 0.0 && encoded == 0.0f))
        throw std::runtime_error("Setting is outside the envelope's numeric range");
    std::ostringstream out;
    out.imbue(std::locale::classic());
    out << std::setprecision(std::numeric_limits<float>::max_digits10) << encoded;
    auto result = out.str();
    if (result.find_first_of(".eE") == std::string::npos) result += ".0";
    return result;
}

void validate(settings const& value)
{
    for (auto duration : {value.attack_ms, value.release_ms})
        if (!std::isfinite(duration) || duration < 0.0)
            throw std::runtime_error("Attack/release must be finite, nonnegative milliseconds");
    for (auto level : {value.sustain, value.gain})
        if (!std::isfinite(level) || level < 0.0 || level > 1.0)
            throw std::runtime_error("Sustain/gain must be between 0 and 1");
    (void)real(value.sustain);
    (void)real(value.gain);
    (void)real(value.sustain * value.gain);
    if (value.attack_ms > 0.0 && value.sustain * value.gain > 0.0)
        (void)real(value.sustain * value.gain * 1000.0 / value.attack_ms);
    if (value.release_ms > 0.0) (void)real(value.release_ms / 1000.0);
}
} // namespace

command parse(std::string const& line, settings const& current)
{
    std::istringstream in(line);
    in.imbue(std::locale::classic());
    std::string name, argument, extra;
    in >> name;
    command result{action::apply, current};
    if (name == ":" || name == ":status" || name == ":help") {
        if (in >> extra) throw std::runtime_error("This command takes no argument");
        result.kind = name == ":help" ? action::help : action::status;
        return result;
    }
    if (name != ":a" && name != ":s" && name != ":r" && name != ":g" && name != ":e")
        throw std::runtime_error("Unknown command; use :help");
    if (!(in >> argument) || (in >> extra))
        throw std::runtime_error("Expected one value; use :help");
    if (name == ":e") {
        if (argument != "on" && argument != "off")
            throw std::runtime_error("Use :e on or :e off");
        result.value.enabled = argument == "on";
    } else {
        std::istringstream number(argument);
        number.imbue(std::locale::classic());
        double value;
        if (!(number >> value) || !number.eof() || !std::isfinite(value))
            throw std::runtime_error("Expected a finite decimal number");
        if (name == ":a") result.value.attack_ms = value;
        if (name == ":s") result.value.sustain = value;
        if (name == ":r") result.value.release_ms = value;
        if (name == ":g") result.value.gain = value;
    }
    validate(result.value);
    return result;
}

std::string describe(settings const& value)
{
    std::ostringstream out;
    out.imbue(std::locale::classic());
    out << std::setprecision(9)
        << "Envelope " << (value.enabled ? "on" : "off")
        << "; attack " << value.attack_ms << " ms; sustain " << value.sustain
        << "; release " << value.release_ms << " ms; gain " << value.gain
        << "; note level " << (value.enabled ? value.sustain * value.gain : value.gain);
    return out.str();
}

std::string program(settings const& value)
{
    validate(value);
    double const peak = value.enabled ? value.sustain * value.gain : value.gain;
    bool const attack = value.enabled && value.attack_ms > 0.0 && peak > 0.0;
    bool const release = value.enabled && value.release_ms > 0.0;
    auto start = [&](std::string const& indent) {
        std::string text = indent + "start_note()\n";
        if (attack) {
            text += indent + "set_amplitude(0)\n" + indent + "stage = 1\n";
            text += indent + "ramp(" + real(peak) + ", " +
                    real(peak * 1000.0 / value.attack_ms) + ")\n";
        } else {
            text += indent + "set_amplitude(" + real(peak) + ")\n";
            text += indent + "stage = 2\n";
        }
        text += indent + "led(0, 1, 0, led_level)\n";
        return text;
    };
    std::string text = "# Generated by voicebd terminal controls.\n# " + describe(value) +
        "\n# Attack/release durations are independent of MIDI velocity.\n"
        "# stage: 0 idle, 1 attack, 2 sustain, 3 release, 4 voice steal\n\n"
        "def on_note_on(key, velocity)\n"
        "    state stage\n"
        "    state led_level\n"
        "    led_level = velocity / 127.0\n"
        "    if stage != 0\n"
        "        if stage == 4 return end\n"
        "        stage = 4\n"
        "        ramp(0, 200)  # Existing voice-steal fade: full scale in 5 ms.\n"
        "        return\n"
        "    end\n" + start("    ") + "end\n\n"
        "def on_note_off()\n";
    if (release) {
        text += "    var current = input(INPUT_AMPLITUDE)\n"
                "    if current > 0\n"
                "        stage = 3\n"
                "        ramp(0, current / " + real(value.release_ms / 1000.0) + ")\n"
                "        return\n"
                "    end\n";
    }
    text += "    stage = 0\n"
            "    set_amplitude(0)\n"
            "    led(0, 0, 0, 0)\n"
            "    note_end()\n"
            "end\n\n"
            "def on_ramp_end()\n"
            "    if stage == 4\n" + start("        ") +
            "    elif stage == 3\n"
            "        stage = 0\n"
            "        led(0, 0, 0, 0)\n"
            "        note_end()\n"
            "    elif stage == 1\n"
            "        stage = 2\n"
            "    end\n"
            "end\n";
    return text;
}

void compile(std::filesystem::path const& compiler,
             std::filesystem::path const& source,
             std::filesystem::path const& bytecode)
{
    std::string executable = compiler.string(), input = source.string(), output = bytecode.string();
    char option[] = "-o";
    char* arguments[] = {executable.data(), input.data(), option, output.data(), nullptr};
    pid_t child;
    int const error = posix_spawn(&child, executable.c_str(), nullptr, nullptr, arguments, environ);
    if (error) throw std::runtime_error("Cannot start Berry compiler: " + std::string(std::strerror(error)));
    int status;
    while (waitpid(child, &status, 0) < 0) {
        if (errno == EINTR) continue;
        throw std::runtime_error("Cannot wait for Berry compiler: " + std::string(std::strerror(errno)));
    }
    if (!WIFEXITED(status) || WEXITSTATUS(status) != 0)
        throw std::runtime_error("Berry compilation failed; no program uploaded");
}

} // namespace envelope_controls
